# Experiment settings
experiment_name: "vit_tiny_cifar10_baseline"
seed: 42
device: "cuda"  # or "cpu"

# Data settings
dataset: "cifar10"
data_dir: "./data"
num_workers: 4
train_val_split: 0.9  # 90% train, 10% val from training set

# Model settings
model: "vit_tiny"
num_classes: 10

# Training settings
batch_size: 128
num_epochs: 200
eval_every: 999999  # Evaluate every N epochs (set to large number to disable by default)

# Optimizer settings (will override for each experiment)
optimizer:
  type: "sgd"  # Options: "sgd", "adamw", "muon"
  lr: 0.1
  momentum: 0.9  # For SGD
  weight_decay: 0.0001
  # betas: [0.9, 0.999]  # For AdamW
  # nesterov: true  # For Muon
  # adjust_lr_fn: "original"  # For Muon: "original" or "match_rms_adamw"

# Logging
log_dir: "./experiments/logs"